# Generated by Django 4.1.4 on 2022-12-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamClone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
